// Auto-generated by tools/generateTxFlags.js from rippled's include/xrpl/protocol/TxFlags.h
// Do not hand-edit; re-run scripts/generate-tx-flags.sh instead.

#![allow(non_upper_case_globals, dead_code)]

// Universal Transaction flags:
pub(crate) const tfFullyCanonicalSig: u32 = 0x80000000;
pub(crate) const tfInnerBatchTxn: u32 = 0x40000000;
pub(crate) const tfUniversal: u32 = tfFullyCanonicalSig | tfInnerBatchTxn;

pub(crate) const tfRequireDestTag: u32 = 0x00010000;
pub(crate) const tfOptionalDestTag: u32 = 0x00020000;
pub(crate) const tfRequireAuth: u32 = 0x00040000;
pub(crate) const tfOptionalAuth: u32 = 0x00080000;
pub(crate) const tfDisallowXRP: u32 = 0x00100000;
pub(crate) const tfAllowXRP: u32 = 0x00200000;

pub(crate) const tfPassive: u32 = 0x00010000;
pub(crate) const tfImmediateOrCancel: u32 = 0x00020000;
pub(crate) const tfFillOrKill: u32 = 0x00040000;
pub(crate) const tfSell: u32 = 0x00080000;
pub(crate) const tfHybrid: u32 = 0x00100000;

pub(crate) const tfNoRippleDirect: u32 = 0x00010000;
pub(crate) const tfPartialPayment: u32 = 0x00020000;
pub(crate) const tfLimitQuality: u32 = 0x00040000;

pub(crate) const tfSetfAuth: u32 = 0x00010000;
pub(crate) const tfSetNoRipple: u32 = 0x00020000;
pub(crate) const tfClearNoRipple: u32 = 0x00040000;
pub(crate) const tfSetFreeze: u32 = 0x00100000;
pub(crate) const tfClearFreeze: u32 = 0x00200000;
pub(crate) const tfSetDeepFreeze: u32 = 0x00400000;
pub(crate) const tfClearDeepFreeze: u32 = 0x00800000;

pub(crate) const tfGotMajority: u32 = 0x00010000;
pub(crate) const tfLostMajority: u32 = 0x00020000;

pub(crate) const tfRenew: u32 = 0x00010000;
pub(crate) const tfClose: u32 = 0x00020000;

pub(crate) const tfBurnable: u32 = 0x00000001;
pub(crate) const tfOnlyXRP: u32 = 0x00000002;
pub(crate) const tfTransferable: u32 = 0x00000008;
pub(crate) const tfMutable: u32 = 0x00000010;

pub(crate) const tfMPTCanLock: u32 = 0x00000002;
pub(crate) const tfMPTRequireAuth: u32 = 0x00000004;
pub(crate) const tfMPTCanEscrow: u32 = 0x00000008;
pub(crate) const tfMPTCanTrade: u32 = 0x00000010;
pub(crate) const tfMPTCanTransfer: u32 = 0x00000020;
pub(crate) const tfMPTCanClawback: u32 = 0x00000040;

pub(crate) const tfMPTUnauthorize: u32 = 0x00000001;

pub(crate) const tfMPTLock: u32 = 0x00000001;
pub(crate) const tfMPTUnlock: u32 = 0x00000002;

pub(crate) const tfSellNFToken: u32 = 0x00000001;

pub(crate) const tfLPToken: u32 = 0x00010000;
pub(crate) const tfSingleAsset: u32 = 0x00080000;
pub(crate) const tfTwoAsset: u32 = 0x00100000;
pub(crate) const tfOneAssetLPToken: u32 = 0x00200000;
pub(crate) const tfLimitLPToken: u32 = 0x00400000;
pub(crate) const tfTwoAssetIfEmpty: u32 = 0x00800000;

pub(crate) const tfWithdrawAll: u32 = 0x00020000;
pub(crate) const tfOneAssetWithdrawAll: u32 = 0x00040000;

pub(crate) const tfClawTwoAssets: u32 = 0x00000001;

pub(crate) const tfClearAccountCreateAmount: u32 = 0x00010000;

pub(crate) const tfVaultPrivate: u32 = 0x00010000;
pub(crate) const tfVaultShareNonTransferable: u32 = 0x00020000;

pub(crate) const tfAllOrNothing: u32 = 0x00010000;
pub(crate) const tfOnlyOne: u32 = 0x00020000;
pub(crate) const tfUntilFailure: u32 = 0x00040000;
pub(crate) const tfIndependent: u32 = 0x00080000;

pub(crate) const tfLoanOverpayment: u32 = 0x00010000;

pub(crate) const tfLoanFullPayment: u32 = 0x00020000;
pub(crate) const tfLoanLatePayment: u32 = 0x00040000;

pub(crate) const tfLoanDefault: u32 = 0x00010000;
pub(crate) const tfLoanImpair: u32 = 0x00020000;
pub(crate) const tfLoanUnimpair: u32 = 0x00040000;

pub(crate) const tfImmutable: u32 = 0x00010000;
pub(crate) const tfCodeImmutable: u32 = 0x00020000;
pub(crate) const tfABIImmutable: u32 = 0x00040000;
pub(crate) const tfUndeletable: u32 = 0x00080000;

pub(crate) const tmfMPTCanMutateCanLock: u32 = 0x00000002;
pub(crate) const tmfMPTCanMutateRequireAuth: u32 = 0x00000004;
pub(crate) const tmfMPTCanMutateCanEscrow: u32 = 0x00000008;
pub(crate) const tmfMPTCanMutateCanTrade: u32 = 0x00000010;
pub(crate) const tmfMPTCanMutateCanTransfer: u32 = 0x00000020;
pub(crate) const tmfMPTCanMutateCanClawback: u32 = 0x00000040;
pub(crate) const tmfMPTCanMutateMetadata: u32 = 0x00010000;
pub(crate) const tmfMPTCanMutateTransferFee: u32 = 0x00020000;
pub(crate) const tmfMPTSetCanLock: u32 = 0x00000001;
pub(crate) const tmfMPTClearCanLock: u32 = 0x00000002;
pub(crate) const tmfMPTSetRequireAuth: u32 = 0x00000004;
pub(crate) const tmfMPTClearRequireAuth: u32 = 0x00000008;
pub(crate) const tmfMPTSetCanEscrow: u32 = 0x00000010;
pub(crate) const tmfMPTClearCanEscrow: u32 = 0x00000020;
pub(crate) const tmfMPTSetCanTrade: u32 = 0x00000040;
pub(crate) const tmfMPTClearCanTrade: u32 = 0x00000080;
pub(crate) const tmfMPTSetCanTransfer: u32 = 0x00000100;
pub(crate) const tmfMPTClearCanTransfer: u32 = 0x00000200;
pub(crate) const tmfMPTSetCanClawback: u32 = 0x00000400;
pub(crate) const tmfMPTClearCanClawback: u32 = 0x00000800;
pub(crate) const tfTrustLine: u32 = 0x00000004;
pub(crate) const tfWithdrawSubTx: u32 = tfLPToken
    | tfSingleAsset
    | tfTwoAsset
    | tfOneAssetLPToken
    | tfLimitLPToken
    | tfWithdrawAll
    | tfOneAssetWithdrawAll;
pub(crate) const tfDepositSubTx: u32 =
    tfLPToken | tfSingleAsset | tfTwoAsset | tfOneAssetLPToken | tfLimitLPToken | tfTwoAssetIfEmpty;
pub(crate) const tfSendAmount: u32 = 0x00010000;
pub(crate) const tfSendNFToken: u32 = 0x00020000;
pub(crate) const tfAuthorizeToken: u32 = 0x00040000;

// AccountSet SetFlag/ClearFlag values
pub(crate) const asfRequireDest: u32 = 1;
pub(crate) const asfRequireAuth: u32 = 2;
pub(crate) const asfDisallowXRP: u32 = 3;
pub(crate) const asfDisableMaster: u32 = 4;
pub(crate) const asfAccountTxnID: u32 = 5;
pub(crate) const asfNoFreeze: u32 = 6;
pub(crate) const asfGlobalFreeze: u32 = 7;
pub(crate) const asfDefaultRipple: u32 = 8;
pub(crate) const asfDepositAuth: u32 = 9;
pub(crate) const asfAuthorizedNFTokenMinter: u32 = 10;
pub(crate) const asfDisallowIncomingNFTokenOffer: u32 = 12;
pub(crate) const asfDisallowIncomingCheck: u32 = 13;
pub(crate) const asfDisallowIncomingPayChan: u32 = 14;
pub(crate) const asfDisallowIncomingTrustline: u32 = 15;
pub(crate) const asfAllowTrustLineClawback: u32 = 16;
pub(crate) const asfAllowTrustLineLocking: u32 = 17;
