// GENERATED by tools/generate-host-bindings — do not hand-edit.
// Source: https://github.com/XRPLF/rippled/tree/21560cdf82d02771709d6befedb6b192211cf399
// Regenerate with ./scripts/generate-host-bindings.sh (CI runs it with --check).

/// Every host function the XRPL wasm host exposes to a smart contract, at the wire (FFI) level.
///
/// There is one method per declaration in rippled's `host_functions!` block
/// (`crates/xrpl-host-functions/src/lib.rs`), in the same order, named after its wasm import
/// name. Byte regions (`&[u8]`, `&mut [u8]`, `&str`, `u32`) are passed as a `(ptr, len)` pair;
/// `i32` and `i64` are passed as-is. Every call that can fail returns an `i32`: zero or
/// positive on success, or a negative `crate::host::error_codes` value on failure.
///
/// Implemented by `WasmHostBindings` (real FFI, wasm32 only) and `MockHostBindings` (mockall,
/// tests). Plain native builds use the free-function stubs in `host_bindings_empty.rs`
/// instead, which do not implement this trait.
#[allow(unused)] // Nothing calls the trait on non-wasm targets.
#[cfg_attr(
    all(any(test, feature = "test-host-bindings"), not(target_arch = "wasm32")),
    mockall::automock
)]
pub trait HostBindings {
    /// The sequence number of the ledger being built, as 4 little-endian bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn ldgr_index(&self, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The close time of the parent (last-closed) ledger, as 4 little-endian bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn parent_ldgr_time(&self, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The hash of the parent (last-closed) ledger, as 32 bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn parent_ldgr_hash(&self, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The base fee of the ledger being built, in drops, as 4 little-endian bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn base_fee(&self, out_ptr: *mut u8, out_len: usize) -> i32;

    /// Whether an amendment is enabled. The input is either its 32-byte id or its name;
    /// the answer is `1` if enabled and `0` if not.
    ///
    /// **Gas:** 100
    ///
    /// # Wire parameters
    ///
    /// - `amendment_ptr`, `amendment_len`: the `amendment: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn amendment_enabled(&self, amendment_ptr: *const u8, amendment_len: usize) -> i32;

    /// Load the ledger object with the given 32-byte id into a cache slot, so later
    /// calls can read its fields. `cache_idx` selects the slot (1-based); `0` asks the
    /// host to assign a free one. Answers the slot used.
    ///
    /// **Gas:** 5000
    ///
    /// # Wire parameters
    ///
    /// - `obj_id_ptr`, `obj_id_len`: the `obj_id: &[u8]` region.
    /// - `cache_idx`: `i32`.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn cache_le(&self, obj_id_ptr: *const u8, obj_id_len: usize, cache_idx: i32) -> i32;

    /// The serialized bytes of one field of the transaction being executed, selected
    /// by its `SField` code.
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `field`: `i32`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn tx_field(&self, field: i32, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The serialized bytes of one field of the current (escrow) ledger object.
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `field`: `i32`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn home_le_field(&self, field: i32, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The serialized bytes of one field of a previously cached ledger object,
    /// selected by its cache slot and the field's `SField` code.
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `cache_idx`: `i32`.
    /// - `field`: `i32`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn le_field(&self, cache_idx: i32, field: i32, out_ptr: *mut u8, out_len: usize) -> i32;

    /// The serialized bytes of a nested field of the transaction, reached by a
    /// `locator`: a path of little-endian `i32` steps (so its byte length is a non-zero
    /// multiple of 4).
    ///
    /// **Gas:** 110
    ///
    /// # Wire parameters
    ///
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn tx_inner(
        &self,
        locator_ptr: *const u8,
        locator_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The serialized bytes of a nested field of the current (escrow) ledger object,
    /// reached by a `locator`, as with [`HostBindings::tx_inner`].
    ///
    /// **Gas:** 110
    ///
    /// # Wire parameters
    ///
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn home_le_inner(
        &self,
        locator_ptr: *const u8,
        locator_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The serialized bytes of a nested field of a previously cached ledger object,
    /// selected by its cache slot and reached by a `locator`.
    ///
    /// **Gas:** 110
    ///
    /// # Wire parameters
    ///
    /// - `cache_idx`: `i32`.
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn le_inner(
        &self,
        cache_idx: i32,
        locator_ptr: *const u8,
        locator_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The number of elements in an array field of the transaction, selected by its
    /// `SField` code. Answers the count directly; `NoArray` if the field is not an array.
    ///
    /// **Gas:** 40
    ///
    /// # Wire parameters
    ///
    /// - `field`: `i32`.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn tx_arr_len(&self, field: i32) -> i32;

    /// The number of elements in an array field of the current (escrow) ledger
    /// object, as with [`HostBindings::tx_arr_len`].
    ///
    /// **Gas:** 40
    ///
    /// # Wire parameters
    ///
    /// - `field`: `i32`.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn home_le_arr_len(&self, field: i32) -> i32;

    /// The number of elements in an array field of a previously cached ledger object,
    /// selected by its cache slot and `SField` code.
    ///
    /// **Gas:** 40
    ///
    /// # Wire parameters
    ///
    /// - `cache_idx`: `i32`.
    /// - `field`: `i32`.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn le_arr_len(&self, cache_idx: i32, field: i32) -> i32;

    /// The number of elements in a nested array field of the transaction, reached by a
    /// `locator`.
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn tx_inner_arr_len(&self, locator_ptr: *const u8, locator_len: usize) -> i32;

    /// The number of elements in a nested array field of the current (escrow) ledger
    /// object, reached by a `locator`, as with [`HostBindings::tx_inner_arr_len`].
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn home_le_inner_arr_len(&self, locator_ptr: *const u8, locator_len: usize) -> i32;

    /// The number of elements in a nested array field of a previously cached ledger
    /// object, selected by its cache slot and reached by a `locator`.
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `cache_idx`: `i32`.
    /// - `locator_ptr`, `locator_len`: the `locator: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn le_inner_arr_len(
        &self,
        cache_idx: i32,
        locator_ptr: *const u8,
        locator_len: usize,
    ) -> i32;

    /// Verify `signature` over `message` under `pubkey`. Answers `1` if the signature
    /// is valid, `0` if not, or a negative error.
    ///
    /// **Gas:** 300
    ///
    /// # Wire parameters
    ///
    /// - `message_ptr`, `message_len`: the `message: &[u8]` region.
    /// - `signature_ptr`, `signature_len`: the `signature: &[u8]` region.
    /// - `pubkey_ptr`, `pubkey_len`: the `pubkey: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn check_sig(
        &self,
        message_ptr: *const u8,
        message_len: usize,
        signature_ptr: *const u8,
        signature_len: usize,
        pubkey_ptr: *const u8,
        pubkey_len: usize,
    ) -> i32;

    /// The 32-byte ledger key (keylet) of an account's `AccountRoot`, computed from a
    /// 20-byte account id.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn accountroot_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an AMM, computed from its two assets. Each asset is a byte
    /// slice whose length selects its kind (24 = MPT, 20 = XRP, 40 = issued currency +
    /// issuer).
    ///
    /// **Gas:** 450
    ///
    /// # Wire parameters
    ///
    /// - `asset1_ptr`, `asset1_len`: the `asset1: &[u8]` region.
    /// - `asset2_ptr`, `asset2_len`: the `asset2: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn amm_id(
        &self,
        asset1_ptr: *const u8,
        asset1_len: usize,
        asset2_ptr: *const u8,
        asset2_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Check`, computed from a 20-byte account id and its
    /// sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn check_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Credential`, computed from the 20-byte subject and
    /// issuer account ids and a credential-type byte string.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `subject_ptr`, `subject_len`: the `subject: &[u8]` region.
    /// - `issuer_ptr`, `issuer_len`: the `issuer: &[u8]` region.
    /// - `credential_type_ptr`, `credential_type_len`: the `credential_type: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn credential_id(
        &self,
        subject_ptr: *const u8,
        subject_len: usize,
        issuer_ptr: *const u8,
        issuer_len: usize,
        credential_type_ptr: *const u8,
        credential_type_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Delegate` object, computed from the 20-byte account and
    /// the account it authorizes.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `authorize_ptr`, `authorize_len`: the `authorize: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn delegate_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        authorize_ptr: *const u8,
        authorize_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `DepositPreauth`, computed from the 20-byte account and
    /// the account it authorizes to deposit.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `authorize_ptr`, `authorize_len`: the `authorize: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn deposit_preauth_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        authorize_ptr: *const u8,
        authorize_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an account's `DID`, computed from its 20-byte account id.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn did_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `Escrow`, computed from the 20-byte owner account and
    /// its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn escrow_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `RippleState` (trust line), computed from two 20-byte
    /// account ids and a 20-byte currency.
    ///
    /// **Gas:** 400
    ///
    /// # Wire parameters
    ///
    /// - `account1_ptr`, `account1_len`: the `account1: &[u8]` region.
    /// - `account2_ptr`, `account2_len`: the `account2: &[u8]` region.
    /// - `currency_ptr`, `currency_len`: the `currency: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn trustline_id(
        &self,
        account1_ptr: *const u8,
        account1_len: usize,
        account2_ptr: *const u8,
        account2_len: usize,
        currency_ptr: *const u8,
        currency_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `MPTokenIssuance`, computed from the 20-byte issuer
    /// account and its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `issuer_ptr`, `issuer_len`: the `issuer: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn mpt_issuance_id(
        &self,
        issuer_ptr: *const u8,
        issuer_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `MPToken`, computed from a 24-byte MPT issuance id and
    /// the 20-byte holder account.
    ///
    /// **Gas:** 500
    ///
    /// # Wire parameters
    ///
    /// - `mptid_ptr`, `mptid_len`: the `mptid: &[u8]` region.
    /// - `holder_ptr`, `holder_len`: the `holder: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn mptoken_id(
        &self,
        mptid_ptr: *const u8,
        mptid_len: usize,
        holder_ptr: *const u8,
        holder_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `NFTokenOffer`, computed from the 20-byte owner account
    /// and its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_offer_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `Offer`, computed from the 20-byte owner account and
    /// its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn offer_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of an `Oracle`, computed from the 20-byte owner account and
    /// its document id.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `doc_id_ptr`, `doc_id_len`: the `doc_id: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn oracle_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        doc_id_ptr: *const u8,
        doc_id_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `PayChannel`, computed from the 20-byte source account,
    /// the 20-byte destination account, and the channel's sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `destination_ptr`, `destination_len`: the `destination: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn paychan_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        destination_ptr: *const u8,
        destination_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `PermissionedDomain`, computed from the 20-byte owner
    /// account and its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn permissioned_domain_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `SignerList`, computed from its 20-byte owner account.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn signers_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Ticket`, computed from the 20-byte owner account and
    /// its ticket sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn ticket_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Vault`, computed from the 20-byte owner account and its
    /// sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn vault_id(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Sponsorship`, computed from the 20-byte sponsor account
    /// and the 20-byte sponsee account.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `sponsor_ptr`, `sponsor_len`: the `sponsor: &[u8]` region.
    /// - `sponsee_ptr`, `sponsee_len`: the `sponsee: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn sponsorship_id(
        &self,
        sponsor_ptr: *const u8,
        sponsor_len: usize,
        sponsee_ptr: *const u8,
        sponsee_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `LoanBroker`, computed from the 20-byte owner account and
    /// its sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `owner_ptr`, `owner_len`: the `owner: &[u8]` region.
    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn loan_broker_id(
        &self,
        owner_ptr: *const u8,
        owner_len: usize,
        seq_ptr: *const u8,
        seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 32-byte keylet of a `Loan`, computed from the 32-byte id of its `LoanBroker`
    /// and the loan's sequence number.
    ///
    /// **Gas:** 350
    ///
    /// # Wire parameters
    ///
    /// - `loan_broker_id_ptr`, `loan_broker_id_len`: the `loan_broker_id: &[u8]` region.
    /// - `loan_seq_ptr`, `loan_seq_len`: the `loan_seq: u32` region — four little-endian bytes.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn loan_id(
        &self,
        loan_broker_id_ptr: *const u8,
        loan_broker_id_len: usize,
        loan_seq_ptr: *const u8,
        loan_seq_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The XRPL `sha512Half` of `data`: the first `HASH_LEN` bytes of its SHA-512.
    ///
    /// **Gas:** 2000
    ///
    /// # Wire parameters
    ///
    /// - `data_ptr`, `data_len`: the `data: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn sha512_half(
        &self,
        data_ptr: *const u8,
        data_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// Writes `msg` to the trace log, followed by `data` rendered as `data_type` says.
    ///
    /// The one declaration whose wasm function has **no result**: this node's own log
    /// is its only effect, so a guest is told nothing. An `Err` from a host therefore
    /// reaches it in no form, and only the host-fatal ones do anything at all.
    ///
    /// **Gas:** 30
    ///
    /// # Wire parameters
    ///
    /// - `msg_ptr`, `msg_len`: the `msg: &str` region (UTF-8).
    /// - `data_type`: `i32`, a [`TraceDataType`](crate::host::trace::TraceDataType) code.
    /// - `data_ptr`, `data_len`: the `data: &[u8]` region.
    ///
    /// # Returns
    ///
    /// Nothing: the call cannot fail from the guest's perspective.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn trace(
        &self,
        msg_ptr: *const u8,
        msg_len: usize,
        data_type: i32,
        data_ptr: *const u8,
        data_len: usize,
    );

    /// Stores `data` as the current object's data field, replacing whatever was there,
    /// and returns the number of bytes stored; `DataFieldTooLarge` if it exceeds the
    /// host's limit.
    ///
    /// **Gas:** 1000
    ///
    /// # Wire parameters
    ///
    /// - `data_ptr`, `data_len`: the `data: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn set_data(&self, data_ptr: *const u8, data_len: usize) -> i32;

    /// The URI of the `NFToken` with id `nft_id` (32 bytes) held by the 20-byte
    /// `account`.
    ///
    /// **Gas:** 5000
    ///
    /// # Wire parameters
    ///
    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_uri(
        &self,
        account_ptr: *const u8,
        account_len: usize,
        nft_id_ptr: *const u8,
        nft_id_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The 20-byte issuer account encoded in the `NFToken` id `nft_id` (32 bytes).
    ///
    /// **Gas:** 70
    ///
    /// # Wire parameters
    ///
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_issuer(
        &self,
        nft_id_ptr: *const u8,
        nft_id_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The taxon encoded in the `NFToken` id `nft_id` (32 bytes), as four little-endian
    /// bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_taxon(
        &self,
        nft_id_ptr: *const u8,
        nft_id_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// The flags encoded in the `NFToken` id `nft_id` (32 bytes).
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_flags(&self, nft_id_ptr: *const u8, nft_id_len: usize) -> i32;

    /// The transfer fee encoded in the `NFToken` id `nft_id` (32 bytes).
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_xfer_fee(&self, nft_id_ptr: *const u8, nft_id_len: usize) -> i32;

    /// The sequence number encoded in the `NFToken` id `nft_id` (32 bytes), as four
    /// little-endian bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `nft_id_ptr`, `nft_id_len`: the `nft_id: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn nft_serial(
        &self,
        nft_id_ptr: *const u8,
        nft_id_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
    ) -> i32;

    /// A float built from the signed integer `x` under rounding `mode`.
    ///
    /// **Gas:** 100
    ///
    /// # Wire parameters
    ///
    /// - `x`: `i64`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_from_int(&self, x: i64, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;

    /// A float built from the unsigned integer in the 8-byte region `x` under rounding
    /// `mode`.
    ///
    /// **Gas:** 130
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_from_uint(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// A float built from the serialized `STAmount` in `amount` under rounding `mode`.
    ///
    /// **Gas:** 150
    ///
    /// # Wire parameters
    ///
    /// - `amount_ptr`, `amount_len`: the `amount: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_from_stamount(
        &self,
        amount_ptr: *const u8,
        amount_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// A float built from the serialized `STNumber` in `number` under rounding `mode`.
    ///
    /// **Gas:** 150
    ///
    /// # Wire parameters
    ///
    /// - `number_ptr`, `number_len`: the `number: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_from_stnumber(
        &self,
        number_ptr: *const u8,
        number_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float `x` rounded to a signed integer under rounding `mode`, as eight
    /// little-endian bytes.
    ///
    /// **Gas:** 130
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_to_int(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float `x` split into its mantissa (eight little-endian bytes) and its exponent
    /// (four little-endian bytes), each written to its own output region.
    ///
    /// **Gas:** 130
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `mantissa_out_ptr`, `mantissa_out_len`: the `mantissa_out: &mut [u8]` output region.
    /// - `exponent_out_ptr`, `exponent_out_len`: the `exponent_out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_to_mant_exp(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        mantissa_out_ptr: *mut u8,
        mantissa_out_len: usize,
        exponent_out_ptr: *mut u8,
        exponent_out_len: usize,
    ) -> i32;

    /// A float built from `mantissa` and `exponent` under rounding `mode`.
    ///
    /// **Gas:** 100
    ///
    /// # Wire parameters
    ///
    /// - `mantissa`: `i64`.
    /// - `exponent`: `i32`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_from_mant_exp(
        &self,
        mantissa: i64,
        exponent: i32,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// Compares floats `x` and `y`, answering the `FloatOrdering` that places `x`
    /// against `y`. Reaches the guest as that variant's code, **not `memcmp`'s sign**.
    ///
    /// **Gas:** 80
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `y_ptr`, `y_len`: the `y: &[u8]` region.
    ///
    /// # Returns
    ///
    /// The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_cmp(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        y_ptr: *const u8,
        y_len: usize,
    ) -> i32;

    /// The float sum `x + y` under rounding `mode`.
    ///
    /// **Gas:** 160
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `y_ptr`, `y_len`: the `y: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_add(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        y_ptr: *const u8,
        y_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float difference `x - y` under rounding `mode`.
    ///
    /// **Gas:** 160
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `y_ptr`, `y_len`: the `y: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_sub(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        y_ptr: *const u8,
        y_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float product `x * y` under rounding `mode`.
    ///
    /// **Gas:** 300
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `y_ptr`, `y_len`: the `y: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_mult(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        y_ptr: *const u8,
        y_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float quotient `x / y` under rounding `mode`.
    ///
    /// **Gas:** 300
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `y_ptr`, `y_len`: the `y: &[u8]` region.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_div(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        y_ptr: *const u8,
        y_len: usize,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;

    /// The float `x` raised to the power `n` under rounding `mode`.
    ///
    /// **Gas:** 5500
    ///
    /// # Wire parameters
    ///
    /// - `x_ptr`, `x_len`: the `x: &[u8]` region.
    /// - `n`: `i32`.
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    /// - `mode`: `i32`.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn float_pow(
        &self,
        x_ptr: *const u8,
        x_len: usize,
        n: i32,
        out_ptr: *mut u8,
        out_len: usize,
        mode: i32,
    ) -> i32;
}
