// GENERATED by tools/generate-host-bindings — do not hand-edit.
// Source: https://github.com/XRPLF/rippled/tree/21560cdf82d02771709d6befedb6b192211cf399
// Regenerate with ./scripts/generate-host-bindings.sh (CI runs it with --check).

/// Invokes `$callback!` once with the wire signature of every host function, in rippled's
/// declaration order, as `fn name(param: Ty, ...) -> Ret;` items where `Ret` is `i32` or `()`.
///
/// The one list the three `HostBindings` implementations expand from.
macro_rules! for_each_host_function {
    ($callback:ident) => {
        $callback! {
            fn ldgr_index(out_ptr: *mut u8, out_len: usize) -> i32;
            fn parent_ldgr_time(out_ptr: *mut u8, out_len: usize) -> i32;
            fn parent_ldgr_hash(out_ptr: *mut u8, out_len: usize) -> i32;
            fn base_fee(out_ptr: *mut u8, out_len: usize) -> i32;
            fn amendment_enabled(amendment_ptr: *const u8, amendment_len: usize) -> i32;
            fn cache_le(obj_id_ptr: *const u8, obj_id_len: usize, cache_idx: i32) -> i32;
            fn tx_field(field: i32, out_ptr: *mut u8, out_len: usize) -> i32;
            fn home_le_field(field: i32, out_ptr: *mut u8, out_len: usize) -> i32;
            fn le_field(cache_idx: i32, field: i32, out_ptr: *mut u8, out_len: usize) -> i32;
            fn tx_inner(locator_ptr: *const u8, locator_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn home_le_inner(locator_ptr: *const u8, locator_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn le_inner(cache_idx: i32, locator_ptr: *const u8, locator_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn tx_arr_len(field: i32) -> i32;
            fn home_le_arr_len(field: i32) -> i32;
            fn le_arr_len(cache_idx: i32, field: i32) -> i32;
            fn tx_inner_arr_len(locator_ptr: *const u8, locator_len: usize) -> i32;
            fn home_le_inner_arr_len(locator_ptr: *const u8, locator_len: usize) -> i32;
            fn le_inner_arr_len(cache_idx: i32, locator_ptr: *const u8, locator_len: usize) -> i32;
            fn check_sig(message_ptr: *const u8, message_len: usize, signature_ptr: *const u8, signature_len: usize, pubkey_ptr: *const u8, pubkey_len: usize) -> i32;
            fn accountroot_id(account_ptr: *const u8, account_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn amm_id(asset1_ptr: *const u8, asset1_len: usize, asset2_ptr: *const u8, asset2_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn check_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn credential_id(subject_ptr: *const u8, subject_len: usize, issuer_ptr: *const u8, issuer_len: usize, credential_type_ptr: *const u8, credential_type_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn delegate_id(account_ptr: *const u8, account_len: usize, authorize_ptr: *const u8, authorize_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn deposit_preauth_id(account_ptr: *const u8, account_len: usize, authorize_ptr: *const u8, authorize_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn did_id(account_ptr: *const u8, account_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn escrow_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn trustline_id(account1_ptr: *const u8, account1_len: usize, account2_ptr: *const u8, account2_len: usize, currency_ptr: *const u8, currency_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn mpt_issuance_id(issuer_ptr: *const u8, issuer_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn mptoken_id(mptid_ptr: *const u8, mptid_len: usize, holder_ptr: *const u8, holder_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn nft_offer_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn offer_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn oracle_id(account_ptr: *const u8, account_len: usize, doc_id_ptr: *const u8, doc_id_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn paychan_id(account_ptr: *const u8, account_len: usize, destination_ptr: *const u8, destination_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn permissioned_domain_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn signers_id(account_ptr: *const u8, account_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn ticket_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn vault_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn sponsorship_id(sponsor_ptr: *const u8, sponsor_len: usize, sponsee_ptr: *const u8, sponsee_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn loan_broker_id(owner_ptr: *const u8, owner_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn loan_id(loan_broker_id_ptr: *const u8, loan_broker_id_len: usize, loan_seq_ptr: *const u8, loan_seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn sha512_half(data_ptr: *const u8, data_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn trace(msg_ptr: *const u8, msg_len: usize, data_type: i32, data_ptr: *const u8, data_len: usize) -> ();
            fn set_data(data_ptr: *const u8, data_len: usize) -> i32;
            fn nft_uri(account_ptr: *const u8, account_len: usize, nft_id_ptr: *const u8, nft_id_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn nft_issuer(nft_id_ptr: *const u8, nft_id_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn nft_taxon(nft_id_ptr: *const u8, nft_id_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn nft_flags(nft_id_ptr: *const u8, nft_id_len: usize) -> i32;
            fn nft_xfer_fee(nft_id_ptr: *const u8, nft_id_len: usize) -> i32;
            fn nft_serial(nft_id_ptr: *const u8, nft_id_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
            fn float_from_int(x: i64, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_from_uint(x_ptr: *const u8, x_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_from_stamount(amount_ptr: *const u8, amount_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_from_stnumber(number_ptr: *const u8, number_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_to_int(x_ptr: *const u8, x_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_to_mant_exp(x_ptr: *const u8, x_len: usize, mantissa_out_ptr: *mut u8, mantissa_out_len: usize, exponent_out_ptr: *mut u8, exponent_out_len: usize) -> i32;
            fn float_from_mant_exp(mantissa: i64, exponent: i32, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_cmp(x_ptr: *const u8, x_len: usize, y_ptr: *const u8, y_len: usize) -> i32;
            fn float_add(x_ptr: *const u8, x_len: usize, y_ptr: *const u8, y_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_sub(x_ptr: *const u8, x_len: usize, y_ptr: *const u8, y_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_mult(x_ptr: *const u8, x_len: usize, y_ptr: *const u8, y_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_div(x_ptr: *const u8, x_len: usize, y_ptr: *const u8, y_len: usize, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
            fn float_pow(x_ptr: *const u8, x_len: usize, n: i32, out_ptr: *mut u8, out_len: usize, mode: i32) -> i32;
        }
    };
}
