//! Renders the two generated files. Output is pre-`rustfmt`; the binary formats it.

use std::collections::HashMap;

use crate::docs::rewrite_doc_line;
use crate::lower::{wire_params, wire_return};
use crate::parse::{Declared, HostFunction, Param, Return};

fn header(source_label: &str) -> String {
    format!(
        "// GENERATED by tools/generate-host-bindings — do not hand-edit.\n\
         // Source: {source_label}\n\
         // Regenerate with ./scripts/generate-host-bindings.sh (CI runs it with --check).\n"
    )
}

const LIST_DOC: &str = "\
/// Invokes `$callback!` once with the wire signature of every host function, in rippled's
/// declaration order, as `fn name(param: Ty, ...) -> Ret;` items where `Ret` is `i32` or `()`.
///
/// The one list the three `HostBindings` implementations expand from.
";

/// `host_bindings_list.rs`: the `for_each_host_function!` callback macro.
pub fn emit_list(fns: &[HostFunction], source_label: &str) -> Result<String, String> {
    let mut out = header(source_label);
    out.push('\n');
    out.push_str(LIST_DOC);
    out.push_str(
        "macro_rules! for_each_host_function {\n    ($callback:ident) => {\n        $callback! {\n",
    );
    for f in fns {
        out.push_str(&format!(
            "            fn {}({}) -> {};\n",
            f.wasm_name,
            render_params(f)?,
            wire_return(f)
        ));
    }
    out.push_str("        }\n    };\n}\n");
    Ok(out)
}

const TRAIT_PREAMBLE: &str = "\
/// Every host function the XRPL wasm host exposes to a smart contract, at the wire (FFI) level.
///
/// One method per declaration in rippled's `host_functions!` block
/// (`crates/xrpl-host-functions/src/lib.rs`), in declaration order, named by its wasm import
/// name. Regions (`&[u8]`, `&mut [u8]`, `&str`, `u32`) travel as `(ptr, len)` pairs; `i32` and
/// `i64` pass through; every fallible call returns an `i32` that is non-negative on success
/// and a negative `crate::host::error_codes` value on failure.
///
/// Implemented by `WasmHostBindings` (real FFI, wasm32 only), the no-op stubs in
/// `host_bindings_empty.rs` (plain native builds), and `MockHostBindings` (mockall, tests).
#[allow(unused)] // To remove warn when compiled for non-WASM targets
#[cfg_attr(
    all(any(test, feature = \"test-host-bindings\"), not(target_arch = \"wasm32\")),
    mockall::automock
)]
pub trait HostBindings {
";

/// `host_bindings_trait.rs`: the viewable trait.
pub fn emit_trait(fns: &[HostFunction], source_label: &str) -> Result<String, String> {
    let rust_to_wasm: HashMap<String, String> = fns
        .iter()
        .map(|f| (f.rust_name.clone(), f.wasm_name.clone()))
        .collect();

    let mut out = header(source_label);
    out.push('\n');
    out.push_str(TRAIT_PREAMBLE);
    for (i, f) in fns.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        for line in &f.docs {
            out.push_str(&format!(
                "    ///{}\n",
                rewrite_doc_line(line, &rust_to_wasm)
            ));
        }
        out.push_str("    ///\n");
        out.push_str(&format!("    /// **Gas:** {}\n", f.gas));
        out.push_str("    ///\n    /// # Wire parameters\n    ///\n");
        if f.params.is_empty() {
            out.push_str("    /// None.\n");
        }
        for p in &f.params {
            out.push_str(&format!("    /// {}\n", param_bullet(p)));
        }
        out.push_str("    ///\n    /// # Returns\n    ///\n");
        out.push_str(&format!("    /// {}\n", returns_text(f.returns)));
        out.push_str("    ///\n    /// # Safety\n    ///\n");
        out.push_str("    /// Caller must ensure all pointer parameters point to valid memory.\n");

        let params = render_params(f)?;
        let receiver = if params.is_empty() {
            "&self".to_string()
        } else {
            format!("&self, {params}")
        };
        let arrow = match f.returns {
            Return::Unit => "",
            Return::Len | Return::Value => " -> i32",
        };
        out.push_str(&format!(
            "    unsafe fn {}({receiver}){arrow};\n",
            f.wasm_name
        ));
    }
    out.push_str("}\n");
    Ok(out)
}

fn render_params(f: &HostFunction) -> Result<String, String> {
    Ok(wire_params(f)?
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ty))
        .collect::<Vec<_>>()
        .join(", "))
}

fn param_bullet(p: &Param) -> String {
    let n = &p.name;
    match p.declared {
        Declared::Bytes => format!("- `{n}_ptr`, `{n}_len`: the `{n}: &[u8]` region."),
        Declared::Str => format!("- `{n}_ptr`, `{n}_len`: the `{n}: &str` region (UTF-8)."),
        Declared::U32 => {
            format!("- `{n}_ptr`, `{n}_len`: the `{n}: u32` region — four little-endian bytes.")
        }
        Declared::MutBytes => {
            format!("- `{n}_ptr`, `{n}_len`: the `{n}: &mut [u8]` output region.")
        }
        Declared::I32 => format!("- `{n}`: `i32`."),
        Declared::I64 => format!("- `{n}`: `i64`."),
        Declared::TraceDataType => {
            format!("- `{n}`: `i32`, a [`TraceDataType`](crate::host::trace::TraceDataType) code.")
        }
    }
}

fn returns_text(r: Return) -> &'static str {
    match r {
        Return::Len => {
            "The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure."
        }
        Return::Value => {
            "The host's answer on success; a negative error code (see `crate::host::error_codes`) on failure."
        }
        Return::Unit => "Nothing: the call cannot fail from the guest's perspective.",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_host_functions;
    use crate::test_fixtures::SNIPPET;

    const HEADER: &str = "\
// GENERATED by tools/generate-host-bindings — do not hand-edit.
// Source: test
// Regenerate with ./scripts/generate-host-bindings.sh (CI runs it with --check).
";

    #[test]
    fn list_is_one_callback_macro_with_every_wire_signature() {
        let fns = parse_host_functions(SNIPPET).unwrap();
        let expected = format!(
            "{HEADER}
/// Invokes `$callback!` once with the wire signature of every host function, in rippled's
/// declaration order, as `fn name(param: Ty, ...) -> Ret;` items where `Ret` is `i32` or `()`.
///
/// The one list the three `HostBindings` implementations expand from.
macro_rules! for_each_host_function {{
    ($callback:ident) => {{
        $callback! {{
            fn ldgr_index(out_ptr: *mut u8, out_len: usize) -> i32;
            fn trace(msg_ptr: *const u8, msg_len: usize, data_type: i32, data_ptr: *const u8, data_len: usize) -> ();
            fn check_id(account_ptr: *const u8, account_len: usize, seq_ptr: *const u8, seq_len: usize, out_ptr: *mut u8, out_len: usize) -> i32;
        }}
    }};
}}
"
        );
        assert_eq!(emit_list(&fns, "test").unwrap(), expected);
    }

    #[test]
    fn trait_starts_with_header_and_the_automock_attribute() {
        let fns = parse_host_functions(SNIPPET).unwrap();
        let out = emit_trait(&fns, "test").unwrap();
        assert!(out.starts_with(HEADER), "{out}");
        assert!(out.contains("mockall::automock"), "{out}");
        assert!(out.contains("pub trait HostBindings {\n"), "{out}");
        assert!(out.ends_with("}\n"), "{out}");
    }

    #[test]
    fn trait_method_has_verbatim_docs_then_generated_sections() {
        let fns = parse_host_functions(SNIPPET).unwrap();
        let out = emit_trait(&fns, "test").unwrap();
        // No `"\` continuation here: it would strip the first line's indentation.
        let expected = "    /// The sequence number of the ledger being built, as 4 little-endian bytes.
    ///
    /// **Gas:** 60
    ///
    /// # Wire parameters
    ///
    /// - `out_ptr`, `out_len`: the `out: &mut [u8]` output region.
    ///
    /// # Returns
    ///
    /// The number of bytes written on success; a negative error code (see `crate::host::error_codes`) on failure.
    ///
    /// # Safety
    ///
    /// Caller must ensure all pointer parameters point to valid memory.
    unsafe fn ldgr_index(&self, out_ptr: *mut u8, out_len: usize) -> i32;
";
        assert!(out.contains(expected), "{out}");
    }

    #[test]
    fn unit_return_has_no_arrow_and_links_are_rewritten() {
        let fns = parse_host_functions(SNIPPET).unwrap();
        let out = emit_trait(&fns, "test").unwrap();
        assert!(
            out.contains("    /// Writes `msg` to the trace log, see [`HostBindings::ldgr_index`] and `HASH_LEN`.\n"),
            "{out}"
        );
        assert!(
            out.contains("    /// - `data_type`: `i32`, a [`TraceDataType`](crate::host::trace::TraceDataType) code.\n"),
            "{out}"
        );
        assert!(
            out.contains("    /// Nothing: the call cannot fail from the guest's perspective.\n"),
            "{out}"
        );
        assert!(
            out.contains("    unsafe fn trace(&self, msg_ptr: *const u8, msg_len: usize, data_type: i32, data_ptr: *const u8, data_len: usize);\n"),
            "{out}"
        );
    }

    #[test]
    fn u32_region_bullet_explains_the_encoding() {
        let fns = parse_host_functions(SNIPPET).unwrap();
        let out = emit_trait(&fns, "test").unwrap();
        assert!(
            out.contains("    /// - `seq_ptr`, `seq_len`: the `seq: u32` region — four little-endian bytes.\n"),
            "{out}"
        );
        assert!(
            out.contains("    /// - `account_ptr`, `account_len`: the `account: &[u8]` region.\n"),
            "{out}"
        );
    }
}
