// Auto-generated by tools/generateSFields.js from rippled's include/xrpl/protocol/SField.h
// Do not hand-edit; re-run scripts/generate-sfields.sh instead.

// pub const STI_UNKNOWN: u8 = -2;

// pub const STI_NOTPRESENT: u8 = 0;
pub const STI_UINT16: u8 = 1;
pub const STI_UINT32: u8 = 2;
pub const STI_UINT64: u8 = 3;
pub const STI_UINT128: u8 = 4;
pub const STI_UINT256: u8 = 5;
pub const STI_AMOUNT: u8 = 6;
pub const STI_VL: u8 = 7;
pub const STI_ACCOUNT: u8 = 8;
pub const STI_NUMBER: u8 = 9;
pub const STI_INT32: u8 = 10;
pub const STI_INT64: u8 = 11;

pub const STI_OBJECT: u8 = 14;
pub const STI_ARRAY: u8 = 15;
pub const STI_UINT8: u8 = 16;
pub const STI_UINT160: u8 = 17;
pub const STI_PATHSET: u8 = 18;
pub const STI_VECTOR256: u8 = 19;
pub const STI_UINT96: u8 = 20;
pub const STI_UINT192: u8 = 21;
pub const STI_UINT384: u8 = 22;
pub const STI_UINT512: u8 = 23;
pub const STI_ISSUE: u8 = 24;
pub const STI_XCHAIN_BRIDGE: u8 = 25;
pub const STI_CURRENCY: u8 = 26;
pub const STI_DATA: u8 = 27;
pub const STI_DATATYPE: u8 = 28;
pub const STI_JSON: u8 = 29;

// The following type codes are outside the u8 range and are not valid for SField<u8, CODE>
// pub const STI_TRANSACTION: u8 = 10001;
// pub const STI_LEDGERENTRY: u8 = 10002;
// pub const STI_VALIDATION: u8 = 10003;
// pub const STI_METADATA: u8 = 10004;
