if (process.argv.length != 3 && process.argv.length != 4) {
  console.error(
    "Usage: " +
      process.argv[0] +
      " " +
      process.argv[1] +
      " path/to/rippled [path/to/pipe/to]",
  )
  console.error(
    "path/to/rippled may also be a GitHub URL, e.g. https://github.com/XRPLF/rippled or https://github.com/XRPLF/rippled/tree/HEAD",
  )
  process.exit(1)
}

////////////////////////////////////////////////////////////////////////
//  Get all necessary files from rippled
////////////////////////////////////////////////////////////////////////
const path = require("path")
const fs = require("fs/promises")

async function readFileFromGitHub(repo, filename) {
  if (!repo.includes("tree")) {
    repo += "/tree/HEAD"
  }
  let url = repo.replace("github.com", "raw.githubusercontent.com")
  url = url.replace("tree/", "")
  url += "/" + filename

  if (!url.startsWith("http")) {
    url = "https://" + url
  }

  try {
    const response = await fetch(url)
    if (!response.ok) {
      throw new Error(`${response.status} ${response.statusText}`)
    }
    return await response.text()
  } catch (e) {
    console.error(`Error reading ${url}: ${e.message}`)
    process.exit(1)
  }
}

async function readFile(folder, filename) {
  const filePath = path.join(folder, filename)
  try {
    return await fs.readFile(filePath, "utf-8")
  } catch (e) {
    throw new Error(`File not found: ${filePath}, ${e.message}`)
  }
}

const read = (() => {
  try {
    const url = new URL(process.argv[2])
    return url.hostname === "github.com" ? readFileFromGitHub : readFile
  } catch {
    return readFile // Default to readFile if process.argv[2] is not a valid URL
  }
})()

// Strip C-style block comments so commented-out/deprecated/reserved entries
// (e.g. `/* ASF_FLAG(asfTshCollect, 11) */`) are never mistaken for real ones.
function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\r\n]*/g, "")
}

// Join backslash-newline continuations (used throughout the XMACRO body) into
// a single line so regexes don't need to account for line breaks mid-token.
function joinContinuations(text) {
  return text.replace(/\\\r?\n/g, " ")
}

function isNumericLiteral(token) {
  return /^0x[0-9a-fA-F]+$/.test(token) || /^\d+$/.test(token)
}

async function main() {
  // Keep the raw (un-stripped) text for locating section boundaries by
  // searching for "// clang-format on" -- stripping comments first would
  // delete the very marker being searched for.
  const txFlagsFileRaw = await read(
    process.argv[2],
    "include/xrpl/protocol/TxFlags.h",
  )
  const ledgerFormatsFile = stripComments(
    await read(process.argv[2], "include/xrpl/protocol/LedgerFormats.h"),
  )

  // Ledger-object flags (lsf*/lsmf*) that some TF_FLAG entries alias instead
  // of giving their own literal, e.g. TF_FLAG(tfMPTCanLock, lsfMPTCanLock).
  const lsfMap = {}
  for (const [, name, value] of ledgerFormatsFile.matchAll(
    /LSF_FLAG\(\s*(ls[a-zA-Z0-9]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\)/g,
  )) {
    lsfMap[name] = value
  }

  const unresolved = new Set()
  function resolveValue(token) {
    token = token.trim()
    if (isNumericLiteral(token)) return token
    if (lsfMap[token]) return lsfMap[token]
    unresolved.add(token)
    return token // leave symbolic; caller must define it or this won't compile
  }

  // Translate a verbatim C++ boolean/bitwise expression referencing already
  // -emitted names into the Rust equivalent. `~` (bitwise NOT) is the only
  // operator that differs; `|`/`&` and identifiers/hex literals carry over as-is.
  function translateExpr(expr) {
    return expr.trim().replace(/~/g, "!")
  }

  let output = ""
  function addLine(line) {
    output += line + "\n"
  }

  addLine(
    "// Auto-generated by tools/generateSFlags.js from rippled's include/xrpl/protocol/TxFlags.h",
  )
  addLine("// Do not hand-edit; re-run scripts/generate-sflags.sh instead.")
  addLine("")
  addLine("#![allow(non_upper_case_globals)]")
  addLine("")

  ////////////////////////////////////////////////////////////////////////
  //  Universal flags
  ////////////////////////////////////////////////////////////////////////
  addLine("// Universal Transaction flags:")
  addLine("pub const tfFullyCanonicalSig: u32 = 0x80000000;")
  addLine("pub const tfInnerBatchTxn: u32 = 0x40000000;")
  addLine("pub const tfUniversal: u32 = tfFullyCanonicalSig | tfInnerBatchTxn;")
  addLine("pub const tfUniversalMask: u32 = !tfUniversal;")
  addLine("")

  ////////////////////////////////////////////////////////////////////////
  //  Per-transaction flags + masks (the XMACRO(TRANSACTION, TF_FLAG, ...) table)
  ////////////////////////////////////////////////////////////////////////
  const xmacroStart = txFlagsFileRaw.indexOf(
    "#define XMACRO(TRANSACTION, TF_FLAG, TF_FLAG2, MASK_ADJ)",
  )
  const xmacroEnd = txFlagsFileRaw.indexOf("// clang-format on", xmacroStart)
  const xmacroBody = joinContinuations(
    stripComments(txFlagsFileRaw.substring(xmacroStart, xmacroEnd)),
  )

  // Split the macro body into one chunk per TRANSACTION(Name, ...) call.
  const txStarts = [
    ...xmacroBody.matchAll(/TRANSACTION\(\s*([A-Za-z0-9]+)\s*,/g),
  ]
  const emittedFlagNames = new Set()

  for (let i = 0; i < txStarts.length; ++i) {
    const name = txStarts[i][1]
    const blockStart = txStarts[i].index
    const blockEnd =
      i + 1 < txStarts.length ? txStarts[i + 1].index : xmacroBody.length
    const block = xmacroBody.substring(blockStart, blockEnd)

    const maskFlagNames = []

    for (const [, flagName, rawValue] of block.matchAll(
      /TF_FLAG\(\s*([A-Za-z0-9]+)\s*,\s*([^,()]+?)\s*\)/g,
    )) {
      maskFlagNames.push(flagName)
      if (!emittedFlagNames.has(flagName)) {
        emittedFlagNames.add(flagName)
        addLine(`pub const ${flagName}: u32 = ${resolveValue(rawValue)};`)
      }
    }
    for (const [, flagName] of block.matchAll(
      /TF_FLAG2\(\s*([A-Za-z0-9]+)\s*,\s*[^,()]+?\s*\)/g,
    )) {
      // TF_FLAG2 references a flag already defined elsewhere in this same
      // table (e.g. AMMWithdraw reusing AMMDeposit's tfLPToken) -- contributes
      // to this transaction's mask but is not redeclared.
      maskFlagNames.push(flagName)
    }

    const maskAdjMatch = block.match(/MASK_ADJ\(\s*([^)]*)\)/)
    const maskAdj = maskAdjMatch ? maskAdjMatch[1].trim() : "0"

    if (maskFlagNames.length > 0) {
      let expr = `!(tfUniversal | ${maskFlagNames.join(" | ")})`
      if (maskAdj !== "0") {
        expr += ` | ${maskAdj}`
      }
      addLine(`pub const tf${name}Mask: u32 = ${expr};`)
    }
    addLine("")
  }

  // A few standalone constants (e.g. tfSendAmount/tfContractParameterMask)
  // are declared between the XMACRO's closing paren and the "// clang-format
  // on" marker -- textually inside the last TRANSACTION() block's substring,
  // but not matched by TF_FLAG/MASK_ADJ. Recover them by scanning everything
  // after the last real `MASK_ADJ(...)` call in the macro body.
  const maskAdjOccurrences = [...xmacroBody.matchAll(/MASK_ADJ\([^)]*\)\)/g)]
  const xmacroExtra =
    maskAdjOccurrences.length > 0
      ? xmacroBody.substring(
          maskAdjOccurrences[maskAdjOccurrences.length - 1].index +
            maskAdjOccurrences[maskAdjOccurrences.length - 1][0].length,
        )
      : ""

  ////////////////////////////////////////////////////////////////////////
  //  Trailer: additional standalone flags/masks/combos declared directly as
  //  `inline constexpr FlagValue NAME = EXPR;` or `constexpr std::uint32_t
  //  NAME = EXPR;` outside the XMACRO table (MPToken mutable flags, NFToken
  //  legacy masks, AMM sub-tx combos, Contract parameter flags, etc).
  ////////////////////////////////////////////////////////////////////////
  // Drop preprocessor directive lines (#define/#pragma/#undef) -- several of
  // them (e.g. `#define TO_VALUE(name, value) inline constexpr FlagValue name
  // = value;`) are macro *definitions* whose parameter placeholders would
  // otherwise be mistaken for real flag declarations by the regex below.
  const trailer = (
    xmacroExtra + stripComments(txFlagsFileRaw.substring(xmacroEnd))
  )
    .split("\n")
    .filter((line) => !/^\s*#/.test(line))
    .join("\n")
  for (const [, name, rawExpr] of trailer.matchAll(
    /(?:inline constexpr FlagValue|constexpr std::uint32_t)\s+([A-Za-z0-9]+)\s*=\s*([^;]+);/g,
  )) {
    if (emittedFlagNames.has(name)) continue // already covered above
    emittedFlagNames.add(name)

    const expr = rawExpr.trim()
    if (isNumericLiteral(expr)) {
      addLine(`pub const ${name}: u32 = ${expr};`)
    } else if (!expr.includes("|") && !expr.includes("~") && lsfMap[expr]) {
      // Bare alias of an lsf*/lsmf* ledger-object flag, e.g. `= lsmfMPTCanMutateCanLock;`
      addLine(`pub const ${name}: u32 = ${resolveValue(expr)};`)
    } else {
      addLine(`pub const ${name}: u32 = ${translateExpr(expr)};`)
    }
  }

  ////////////////////////////////////////////////////////////////////////
  //  AccountSet SetFlag/ClearFlag values (asf*)
  ////////////////////////////////////////////////////////////////////////
  addLine("")
  addLine("// AccountSet SetFlag/ClearFlag values")
  for (const [, name, value] of stripComments(txFlagsFileRaw).matchAll(
    /ASF_FLAG\(\s*(asf[A-Za-z0-9]+)\s*,\s*(\d+)\s*\)/g,
  )) {
    addLine(`pub const ${name}: u32 = ${value};`)
  }

  if (unresolved.size > 0) {
    console.warn(
      "Warning: could not resolve these referenced values (left symbolic, will not compile as-is):",
      [...unresolved].join(", "),
    )
  }

  const outputFile =
    process.argv.length == 4
      ? process.argv[3]
      : path.join(__dirname, "../xrpl-wasm-stdlib/src/sflags.rs")
  try {
    await fs.writeFile(outputFile, output, "utf8")
    console.log("File written successfully to", outputFile)
  } catch (err) {
    console.error("Error writing to file:", err)
  }
}

main()
